#!/bin/bash

if [ ${UID} -ne 0 ]; then
    echo "You must be super user to execute this script"
    echo "Exit with errors"
    exit 1
fi

# data
read -e -p "Site url: " A2NEWSITE_SITE
read -e -p "Document root: " A2NEWSITE_DOCUMENT_ROOT
A2NEWSITE_CONF_FILE="100-${A2NEWSITE_SITE}.conf"
if [ -f ${A2NEWSITE_CONF_FILE} ]; then
    echo "File ${A2NEWSITE_CONF_FILE} already exists."
    echo "Exit with errors"
    exit 2
fi

# Create config file
A2NEWSITE_CONFIG_FILE_CONTENT="<VirtualHost *:80>\n\
\tServerName ${A2NEWSITE_SITE}\n\
\tServerAdmin webmaster@localhost\n\
\tDocumentRoot ${A2NEWSITE_DOCUMENT_ROOT}\n\
\t<Directory \"${A2NEWSITE_DOCUMENT_ROOT}\">\n\
\t\tOptions Indexes MultiViews FollowSymLinks\n\
\t\tAllowOverride All\n\
\t\tOrder allow,deny\n\
\t\tAllow from all\n\
\t\t</Directory>\n\
\tErrorLog ${A2NEWSITE_DOCUMENT_ROOT}/error.log\n\
\tCustomLog ${A2NEWSITE_DOCUMENT_ROOT}/access.log combined\n\
</VirtualHost>"

touch "/etc/apache2/sites-available/100-${A2NEWSITE_SITE}.conf"
echo -ne ${A2NEWSITE_CONFIG_FILE_CONTENT} > "etc/apache2/sites-available/100-${A2NEWSITE_SITE}.conf"

echo "Enabling site..."
a2ensite 100-${A2NEWSITE_SITE} >> /dev/null

echo "Restarting apache..."
service apache2 restart >> /dev/null

A2NEWSITE_LINES_IN_HOSTS=`grep ${A2NEWSITE_SITE} /etc/hosts | wc -l`
if [ ${A2NEWSITE_LINES_IN_HOSTS} -eq 0 ]; then
    echo "127.0.0.1 ${A2NEWSITE_SITE}" >> /etc/hosts
fi

echo "Thanks!"

