#!/bin/bash

if [ ${#} -eq 0 ]; then
    echo "You forget to tell me what directory do you want to create"
    exit 1
fi

last_dir=''

while [ ${#} -gt 0 ]; do
    
    last_dir=${1}
    mkdir -p "${1}"
    shift;

done

cd "${last_dir}"
