#!/bin/bash

function mkcdir() {
  if [ ${#} -eq 0 ]; then
      echo "You forget to tell me what directory do you want to create"
  fi

  last_dir=''
  while [ ${#} -gt 0 ]; do
      last_dir=${1}
      mkdir -p "${1}"
      shift;
  done

  cd "${last_dir}"
}

export -f mkcdir
