#!/bin/bash
#########################################
## Nombre:          git-cap
## Description:     git checkout and push
## Version:         0.1
## autor:           Mario Domínguez
#########################################

GIT_CAP_BRANCH=${1}

git checkout master
git pull
git branch ${GIT_CAP_BRANCH}
git checkout ${GIT_CAP_BRANCH}
git push --set-upstream origin ${GIT_CAP_BRANCH}
